name: my_movies
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  get_it: ^7.2.0
  rxdart: ^0.27.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  patrol: ^3.5.0  # Make sure this is only under dev_dependencies
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
