name: Flutter CI

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      - name: Run Patrol tests on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          profile: pixel_6
          emulator-options: -no-snapshot -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          script: |
            dart pub global activate patrol_cli
            export PATH="$PATH:$HOME/.pub-cache/bin"
            flutter build apk --debug
            patrol test --device "emulator-5554" --target integration_test

      - name: Run custom analyzer check
        run: dart run tool/analyze_check.dart

      - name: Build debug APK
        run: flutter build apk --debug
