name: Flutter CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      - name: Analyze code
        run: |
          dart analyze lib --format json > result.json
          ERRORS=$(jq '[.diagnostics[] | select(.severity=="ERROR")] | length' result.json)
          if [ "$ERRORS" -gt 0 ]; then
            echo "❌ Found $ERRORS error(s)"
            cat result.json | jq -r '.diagnostics[] | select(.severity=="ERROR") | "\(.location.file):\(.location.range.start.line):\(.location.range.start.column) - \(.problemMessage)"'
            exit 1
          else
            echo "✅ No errors found"
          fi

      - name: Build debug APK
        run: flutter build apk --debug
